server:
  servlet:
    context-path: /rest
  port: 8080
env: local
application:
  name: demo-spring-boot
  description: This the dummy Spring Boot Application
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rest-api

api-version: api/v1
person:
  name: Sudhir
  age: 89
admins:
  persons:
    - name: admin1
      age: 56
    - name: admin2
      age: 60
dbs:
  db1:
    username: admin
    password: password
    host:
      host: localhost
      port: 6890
  db2:
    username: admin1
    password: passworss
    host:
      host: localhost
      port: 9087
web-app-configs:
  - app: web1
    config:
      application-context: /web1/
      web-disto-dir: /Users/sudhiry/yadavsudhir405/angularjs-es/dist
      default-file-name: index.html
  - app: web2
    config:
      application-context: /web2
      web-disto-dir: /opt/rest-api/web2
      default-file-name: index.html

