server:
  servlet:
    context-path: /rest
  port: 8080
env: local
application:
  name: demo-spring-boot
  description: This the dummy Spring Boot Application
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rest-api

api-version: api/v1
rest-api:
  web-app-configs:
    - app: web1
      config:
        applicationContext: /web1
        webDistoDir: /Users/sudhiry/yadavsudhir405/angularjs-es/dist
        defaultFileName: index.html
  person:
    name: CustomPerson
    age: 45
    sex: male
  whiteListedFileType:
    - HTML
    - CSS
    - JPEG
    - JPG
    - JS
    - PDF
    - PNG
  admins:
    - name: Admin1
      age: 22
      sex: male
    - name: Admin2
      age: 45
      sex: FEMALE
  web-apps:
    - app: web1
      config:
        applicationContext: /web1
        webDistoDir: file:/Users/sudhiry/yadavsudhir405/angularjs-es/dist
        defaultFileName: index.html

    - app: web2
      config:
        applicationContext: /web2
        webDistoDir: file:/opt/rest-api/web2
        default-file-name: index.html
  required-services:
    dbs:
      MONGO:
        username: admin
        password: admin
        host:
          host: 192.168.0.1
          port: 897987
